var myPlaylist = [
    {
        mp3:'Davis/1.mp3',
        title:'1',
        artist:'Davis',
        duration:'5:31',
        buy:'Davis/1.mp3',
        cover:'images/cover.jpg'
    },
    {
        mp3:'Davis/2.mp3',
        title:'2',
        artist:'Davis',
        duration:'4:31',
        buy:'Davis/2.mp3',
        cover:'images/cover.jpg'
    },
    {
        mp3:'Davis/3.mp3',
        title:'3',
        artist:'Davis',
        duration:'4:05',
        buy:'Davis/3.mp3',
        cover:'images/cover.jpg'
    },
    {
        mp3:'Davis/4.mp3',
        title:'4',
        artist:'Davis',
        duration:'2:03',
        buy:'Davis/4.mp3',
        cover:'images/cover.jpg'
    },
    {
        mp3:'Davis/8.mp3',
        title:'8',
        artist:'Davis',
        duration:'5:02',
        buy:'Davis/8.mp3',
        cover:'images/cover.jpg'
    }
];
